# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyRaptor application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.1.2
        poetry config virtualenvs.in-project true
        poetry check
        poetry install
    - name: Lint with pylint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        poetry run pylint --fail-under=7.0 tests pyraptor
    - name: Test with pytest
      run: |
        poetry run pytest tests/
